// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef tf_gui_h
#define tf_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *main_window;
  Fl_Browser *brwsr_run_output;
  Fl_Group *grp_status_bar;
  Fl_Text_Display *txdsp_status_bar;
  void show();
  void start_showing_window();
};
#endif
